### ISSUE TITLE
Problem compiling `which` in multivariate case

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1139] opened 2021-07-08 18:33 UTC
User message to nimble-users on 7/1/21 had this line in a nimbleFunction

`recterr[i] <- which((abs(Distmat[birthterr[i], 1:nterr] - Dist[i])) == min(abs(Distmat[birthterr[i], 1:nterr] - Dist[i])))`

which fails in compilation.

**Comment by perrydv** [comment] 2021-07-29 19:24
Also we should check documentation of `which()`

**Comment by paciorek** [comment] 2021-08-08 21:48
It's documented in Table 11.1.

**Comment by paciorek** [comment] 2021-08-28 19:17
Here's a reprex:

```
Dist <- rgamma(20, 0.8, 1.1) #Movement distances
Distmat <- matrix(nrow = 20, ncol= 40, rgamma(20*40,  0.8, 1.1)) #Matrix of distances between all departure and arrival points
nterr <- dim(Distmat)[2] #Number of departure/arrival points
birthterr <- sample(1:20, 20, replace=T)  #Departure rows

sortbyterr <- nimbleFunction(
  run = function(Distmat = double(2), birthterr = double(1), Dist = double(1), nterr = double()){
    returnType(double(1))
    n1 <- length(Dist)
    recterr <- numeric(length=n1, init=FALSE)
    
    for(i in 1:n1){
      recterr[i] <- which((abs(Distmat[birthterr[i], 1:nterr] - Dist[i])) == min(abs(Distmat[birthterr[i], 1:nterr] - Dist[i])))
    }
    
    return(recterr)
  })

sortbyterr(Distmat, birthterr,Dist, nterr)
cs <- compileNimble(sortbyterr)
cs((Distmat, birthterr,Dist, nterr))
```

The issue is that `which` returns a vector so in this case one needs to append `[1]` to the result of `which` in order to assign to `recterr[i]`. This is the same as other cases where we require a user to subset to get dimensions right when assigning, so not sure there is anything specific we want to do here. @perrydv please weigh in when you have a chance.

Interestingly even though the result of `which` (actually `setWhich` in C++) is integer, it looks like casting to double works fine in the generated C++.

**Comment by paciorek** [comment] 2021-09-18 19:45
Per in-person discussion, we decided this was fine as is, given similarity to other dimension demotion cases.

**Closed by paciorek** 2021-09-18 19:45 UTC
Labels: question
