### ISSUE TITLE
compiler warnings on NERSC edison machine (Suse Linux)

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#214] opened 2016-08-10 16:06 UTC
We get warnings with calls to Eigen in the first test (blocker) in test-mcmc. The R on the machine is old (R3.1.3).

Seems to run fine despite the warnings, so just noting this.

====== blocker test in test-mcmc.R ==================

g++ -I/usr/common/graphics/cascade/1.0/install/lib64/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include" -I/usr/local/include    -fpic  -fPIC  -c P_1_blocker.cpp -o P_1_blocker.o
g++ -I/usr/common/graphics/cascade/1.0/install/lib64/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include" -I/usr/local/include    -fpic  -fPIC  -c P_1_blocker_nfCode.cpp -o P_1_blocker_nfCode.o
In file included from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Core:263:0,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Dense:1,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:29:39: warning: ignoring attributes on template argument '__m128 {aka __vector(4) float}' [-Wignored-attributes]
 template<> struct is_arithmetic<__m128>  { enum { value = true }; };
                                       ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:30:40: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 template<> struct is_arithmetic<__m128i> { enum { value = true }; };
                                        ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:31:40: warning: ignoring attributes on template argument '__m128d {aka __vector(2) double}' [-Wignored-attributes]
 template<> struct is_arithmetic<__m128d> { enum { value = true }; };
                                        ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:101:43: warning: ignoring attributes on template argument 'Eigen::internal::Packet4f {aka __vector(4) float}' [-Wignored-attributes]
 template<> struct unpacket_traits<Packet4f> { typedef float  type; enum {size=4}; };
                                           ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:102:43: warning: ignoring attributes on template argument 'Eigen::internal::Packet2d {aka __vector(2) double}' [-Wignored-attributes]
 template<> struct unpacket_traits<Packet2d> { typedef double type; enum {size=2}; };
                                           ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:103:43: warning: ignoring attributes on template argument 'Eigen::internal::Packet4i {aka __vector(2) long long int}' [-Wignored-attributes]
 template<> struct unpacket_traits<Packet4i> { typedef int    type; enum {size=4}; };
                                           ^
In file included from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Core:263:0,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Dense:1,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:586:35: warning: ignoring attributes on template argument 'Eigen::internal::Packet4f {aka __vector(4) float}' [-Wignored-attributes]
 struct palign_impl<Offset,Packet4f>
                                   ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:609:35: warning: ignoring attributes on template argument 'Eigen::internal::Packet4i {aka __vector(2) long long int}' [-Wignored-attributes]
 struct palign_impl<Offset,Packet4i>
                                   ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/PacketMath.h:632:35: warning: ignoring attributes on template argument 'Eigen::internal::Packet2d {aka __vector(2) double}' [-Wignored-attributes]
 struct palign_impl<Offset,Packet2d>
                                   ^
In file included from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Core:265:0,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Dense:1,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/Complex.h:211:63: warning: ignoring attributes on template argument 'Eigen::internal::Packet4f {aka __vector(4) float}' [-Wignored-attributes]
 template<> struct conj_helper<Packet4f, Packet2cf, false,false>
                                                               ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/Complex.h:220:63: warning: ignoring attributes on template argument 'Eigen::internal::Packet4f {aka __vector(4) float}' [-Wignored-attributes]
 template<> struct conj_helper<Packet2cf, Packet4f, false,false>
                                                               ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/Complex.h:407:63: warning: ignoring attributes on template argument 'Eigen::internal::Packet2d {aka __vector(2) double}' [-Wignored-attributes]
 template<> struct conj_helper<Packet2d, Packet1cd, false,false>
                                                               ^
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/arch/SSE/Complex.h:416:63: warning: ignoring attributes on template argument 'Eigen::internal::Packet2d {aka __vector(2) double}' [-Wignored-attributes]
 template<> struct conj_helper<Packet1cd, Packet2d, false,false>
                                                               ^
In file included from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Core:276:0,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Dense:1,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/src/Core/Functors.h:932:28: warning: 'template<class _Operation> class std::binder2nd' is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder2nd<T> >
                            ^~~~~~~~~
In file included from /opt/gcc/6.1.0/snos/include/g++/bits/stl_function.h:1128:0,
                 from /opt/gcc/6.1.0/snos/include/g++/string:48,
                 from /opt/gcc/6.1.0/snos/include/g++/bits/locale_classes.h:40,
                 from /opt/gcc/6.1.0/snos/include/g++/bits/ios_base.h:41,
                 from /opt/gcc/6.1.0/snos/include/g++/ios:42,
                 from /opt/gcc/6.1.0/snos/include/g++/istream:38,
                 from /opt/gcc/6.1.0/snos/include/g++/sstream:38,
                 from /opt/gcc/6.1.0/snos/include/g++/complex:45,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Core:28,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/Eigen/Dense:1,
                 from /global/u1/p/paciorek/R/x86_64-unknown-linux-gnu-library/3.1/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/opt/gcc/6.1.0/snos/include/g++/backward/binders.h:143:11: note: declared here
     class binder2nd
           ^~~~~~~~~

**Comment by perrydv** [comment] 2016-08-10 23:56
That is coming from Eigen code, which is heavily templatized.  

Maybe it’s time to use pragmas or compiler arguments to disable that warning.

**Comment by perrydv** [comment] 2016-08-11 00:20
There is fairly recent information about this in Eigen discussions here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1221

It appears that changes in gcc trigger this warning from Eigen's code.  

One option is we could upgrade our Eigen.  But since we don't want to worry about unintended consequences of that, we could instead adapt their patch as follows:

#if defined __GNUC__ && __GNUC__>=6
#pragma GCC diagnostic ignored "-Wignored-attributes
#endif

We could put this in something always included such as NimArrBase.h

**Comment by perrydv** [comment] 2016-08-11 00:22
Oops, critically, the previous comment did not use code formatting and hence was inadvertently formatted by markdown.  See edited version.

**Comment by paciorek** [comment] 2016-08-11 00:25
I'd suggest we not worry about it for this release given it's showing up
only on one particular system/Linux variant.  I mainly just wanted to note
it.

**Comment by perrydv** [comment] 2016-08-11 00:28
But we might have a simple fix, and that would save those users from tons of warnings.  Do you want to try putting that #if block of code in on that system?

**Comment by paciorek** [comment] 2016-08-11 00:30
ok, will let you know.

**Comment by paciorek** [comment] 2016-08-11 00:46
That did fix the warnings on edison. I'll make those changes in devel.

**Comment by perrydv** [comment] 2016-08-11 00:51
Ok we just need to check that is doesn’t generate other warnings on other systems, but hopefully the Eigen patch we imitated had the #if check appropriately tailored.

**Comment by paciorek** [comment] 2016-08-14 02:11
ok, these warnings also occur in a Debian machine (using the rocker r-devel image). So we probably need to expand the conditions under which we use this patch. 

docker run --rm -ti rocker/r-base bash

root@3a01d8a6e682:/# cat /etc/issue
Debian GNU/Linux stretch/sid \n \l

root@3a01d8a6e682:/# gcc --version
gcc (Debian 6.1.1-11) 6.1.1 20160802

**Comment by paciorek** [comment] 2016-08-14 03:37
followup - warning only occurs with g++ not clang++.

**Comment by paciorek** [comment] 2016-08-15 21:13
One more note here -

**Comment by paciorek** [comment] 2016-08-15 21:40
So I can't get it to use the pragma such that the warnings are suppressed under Debian + GCC 6, regardless of whether the pragma is within the 'if'.  So I'm worried that for users using GCC 6, they'll get these voluminous warnings (both -Wignored-attributes and -Wdeprecated-declarations) when running compileNimble().

**Comment by perrydv** [comment] 2016-08-22 21:04
I've taken a different path on a branch where I use arguments to system() to suppress routine output of C++ compiler output, so the distressing warnings are not shown.  That seems easier than wrestling with pragmas.   There a nimbleOption to flip compiler output back on.

Can you try upgrading to Eigen 3.2.9?  I think it's just a matter of replacing the Eigen directory contents.  I can't reproduce the warnings or I would try it.  If Eigen handles the various defines and pragmas maybe it will suppress the warnings?

**Comment by paciorek** [comment] 2016-08-22 22:09
Slightly confused. Do we want to test the solution with the current Eigen
on my setup to see if that works?  Or you want us to upgrade Eigen before
the release?

**Comment by perrydv** [comment] 2016-08-22 22:12
Clarification:

Two solutions here: one superficial and one that really handles the problem.

Superficial solution: suppress compiler output from the user's R session.  That seems like a good idea at this point anyway, since we're pretty comfortable with nimble compilation and users don't need to see all that technical stuff.

Handling the real problem: I don't know how to do this easily but I'm wondering if simply updating Eigen will fix it.  Since you are the one who can reproduce the issue I think you would need to see if that works.

If you use my pull-request branch (extern_issue), you will have to set nimbleOptions(suppressCppCompilerOutput = FALSE) to see that output the old-fashioned way.

**Comment by paciorek** [comment] 2016-08-23 21:14
I've confirmed that, not surprisingly, suppressing compiler output works as a superficial solution on the Debian + GCC6 test system I have running in a docker container. 

Will report subsequently on Eigen upgrade.

**Comment by paciorek** [comment] 2016-08-23 21:32
No dice with upgrading Eigen using the extern_issue branch. I'm seeing the same compiler warnings on my Debian+GCC6 test system as before.

Side note: warnings occur under both of the following compilation invocations (the latter set based on ~/.R/Makevars modifications):

g++ -I/usr/share/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/usr/local/lib/R/site-library/nimble/include"     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-NmmxMb/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c P_2_nfRefClass_nimble33.cpp -o P_2_nfRefClass_nimble33.o

g++ -I/usr/share/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/usr/local/lib/R/site-library/nimble/include"     -fpic  -std=c++98 -mtune=native -g -O2 -Wall -pedantic -c P_1_nfRefClass_nimble33.cpp -o P_1_nfRefClass_nimble33.o

**Comment by perrydv** [comment] 2016-08-24 00:09
What happens if you add -Wno-ignored-attributes as the last compiler flag?

**Comment by paciorek** [comment] 2016-08-24 00:26
That helps.

Now the only warnings are about Eigen's indentation practices.

g++ -I/usr/share/R/include -DNDEBUG  -DEIGEN_MPL2_ONLY=1 -I"/usr/local/lib/R/site-library/nimble/include"     -fpic  -std=c++98 -mtune=native -g -O2 -Wall -pedantic -Wno-ignored-attributes -c P_1_blocker_nfCode.cpp -o P_1_blocker_nfCode.o
In file included from /usr/local/lib/R/site-library/nimble/include/Eigen/Core:326:0,
                 from /usr/local/lib/R/site-library/nimble/include/Eigen/Dense:1,
                 from /usr/local/lib/R/site-library/nimble/include/nimble/EigenTypedefs.h:4,
                 from P_1_blocker_nfCode.cpp:3:
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function ‘void Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::operator()(Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar*, Index, const LhsScalar*, const RhsScalar*, Index, Index, Index, Eigen::internal::gebp_kernel<LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs>::ResScalar, Index, Index, Index, Index, RhsScalar*)’:
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:574:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(nr==4) traits.initAcc(C3);
         ^~
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:575:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                   traits.initAcc(C4);
                   ^~~~~~
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:946:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(nr==4) R3 = ploadu<ResPacket>(r3);
         ^~
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:948:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                   traits.acc(C0, alphav, R0);
                   ^~~~~~
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:951:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(nr==4) traits.acc(C3, alphav, R3);
         ^~
/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:953:19: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                   pstoreu(r0, R0);
                   ^~~~~~~
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o P_1_blocker08_24_00_22_17.so P_1_blocker.o P_1_blocker_nfCode.o -L/usr/local/lib/R/site-library/nimble/CppCode -lnimble -Wl,-rpath=/usr/local/lib/R/site-library/nimble/CppCode -llapack -lblas -L/usr/lib/R/lib -lR
done compiling model

**Comment by perrydv** [comment] 2016-08-24 00:39
We could either change the indentation in nimble's copy of eigen or try -Wno-misleading-indentation

**Comment by paciorek** [comment] 2016-08-24 01:23
Yeah, I was musing about which of those options are best. I don't relish the idea of modifying a distinct package even if it is an easy change. So I think I'd vote for the additional flag. 

I tested putting that into PKG_CPPFLAGS in inst/make/Makevars_lib.in and that worked. (I'll need to put in inst/make/Makevars.in to handle the case where we are not creating libnimble.so.)

If we include these invocations that try to match what CRAN build machine has:
CXXFLAGS=-std=c++98 -mtune=native -g -O2 -Wall -pedantic
then everything is fine.
If we don't include those invocations then we also need -Wno-deprecated-declarations. 

So here's where we are. I think we want:
1) -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations
in inst/make/Makevars_lib.in
2) I think I would vote to set nimbleOptions(suppressCppCompilerOutput = FALSE) as the default to keep behavior as it has been. I think it may be useful for some folks to realize when compilation is happening.

**Comment by paciorek** [comment] 2016-08-24 01:31
Also add -Wno... to Makevars.win.in presumably.

**Comment by perrydv** [comment] 2016-08-25 01:26
Now on OS X I get:

warning: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Wunknown-warning-option]

I am going to try adding -Wno-unknown-warning-option

**Comment by duncantl** [comment] 2016-08-25 01:30
On OSX (and other OSes), the compiler and its version are really important for these options/flags. We can test the characteristics of the compiler in the configure script if necessary.
Is this clang or gcc? and which version ?

**Comment by paciorek** [comment] 2016-08-25 01:34
regarding Perry's question, I was getting errors like this on debian+GCC6
when I didn't have the -Wno-misleading-indentation:

/usr/local/lib/R/site-library/nimble/include/Eigen/src/Core/products/GeneralBlockPanelKernel.h:946:9:
warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if(nr==4) R3 = ploadu<ResPacket>(r3);

**Comment by paciorek** [comment] 2016-08-25 01:41
I think that -Wno-misleading-indentation not being a valid option is a clang++ thing. I'm seeing the same thing Perry is seeing, but when using clang++ on my Debian+GCC6 test system.

**Comment by paciorek** [comment] 2016-08-25 01:46
Duncan, given that a user can change .R/Makevars to have CXX=clang++ after installing Nimble using gcc, I'm not seeing how testing the compiler in the configure script will address this fully, but perhaps we just want to set things up so things are fine with whatever compiler was used at time of package installation...

**Comment by paciorek** [comment] 2016-08-25 01:57
Adding -Wno-unknown-warning-option in inst/make/Makevars{,_lib}.in worked for me with clang++.

That said we seem to be in a bit of a rabbit hole in terms of suppressing compiler warnings...

**Comment by perrydv** [comment] 2016-08-25 02:09
Response to Duncan's question: It seems hard to anticipate all compiler varieties in advance.  Is your suggestion that we could write a script that would test whether a compiler can handle a certain flag or generates a certain kind of warning empirically, by calling the compiler?

**Comment by duncantl** [comment] 2016-08-25 02:57
Absolutely, when people mess with things after installation, they are on their own.
And of course, they can also install a binary using clang, but have g++ on their own system.
Binaries mean "you get what you get".

**Comment by duncantl** [comment] 2016-08-25 03:00
As for the rabbit hole....... Yes, if possible, it would be much, much better to make the code correct for all compilers so that none complained. Supressing error messages hides others.  But of course, we do have a wide variety of C++ compilers.  The joy of a standard. Reminds me of Windows 3, NT 7, Vista, ....

**Comment by paciorek** [comment] 2016-08-30 00:55
For the CRAN release the plan is to not print g++ calls or output by default, and to include -Wno-misleading-indentation -Wno-ignored-attributes -Wno-deprecated-declarations
in the Makevars*in files to reduce the number of warnings printed out to being a single warning about a missing option rather than multiple warnings from individual lines of code.

Concern is that checking for valid flags in configure stage could cause a user's installation to fail if there is an issue with the configure for a given system, while adding an unknown -W simply causes a warning at run-time.

It's worth revisiting this with Duncan so I'm leaving this issue open.

**Comment by paciorek** [comment] 2016-09-08 15:13
One other note here:  Writing R extensions says we should not use "-W" flags in Makevars because they are GCC specific.  That brings us back to checking what compiler is being used via configure.

**Comment by paciorek** [comment] 2016-09-08 17:12
Per Skype discussion, one possibility here (to consider down the road) instead of modifying configure.ac to check validity of compiler flags is to write a script that we put in inst/make. That script would presumably be run once at run-time and would provide info to compileNimble (perhaps via having the script inject information into an environment in the nimble namespace) on what flags to use. Some details here on whether it would be used to generate a local Makevars - I think Perry said this is only done in binary installs.

**Comment by perrydv** [comment] 2016-10-05 16:22
I'm closing this because we have a workable solution on compiler warnings. The larger topic of handling many different compilers correctly is something we'll have to revisit, but that's not a specific issue such as the one that started this thread.

**Closed by perrydv** 2016-10-05 16:22 UTC
