### ISSUE TITLE
Issue with assigning deterministic weights[i] <- 1 for dcar_normal() distribution

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#391] opened 2017-05-31 13:21 UTC
Compilation error while compiling MCMC algorithm, depending on how weights (vector) argument for dcar_normal() distribution is defined.

If you define it within a loop of deterministic (scalar) declarations, as is commonly done in WingBUGS code, compilation fails.

If you provide `weights` as a constants vector, compilation gets through.

Reproducible example:

NOTE: checkout branch `car`, and build package there.

```
library(nimble)

code <- nimbleCode({
    for(i in 1:L) {   weights[i] <- 1   }
    S[1:N] ~ car.normal(adj[1:L], weights[1:L], num[1:N], 3)
    for(i in 1:N) {
	Y[i] ~ dnorm(S[i], 1)
    }
})

constants <- list(
    N = 3,
    num = c(1,2,1),
    adj = c(2,   1,3,    2),
    ##weights = rep(1,4),
    L = 4
)

data <- list(
    Y = c(1,2,3)
)

inits <- list(
    S = c(0,0,0)
)

Rmodel <- nimbleModel(code, constants, data, inits)

conf <- configureMCMC(Rmodel)
conf$printSamplers()
Rmcmc <- buildMCMC(conf)

Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)    ## fails here

## There is an error involving the type of neighborWeights.  Going into browser().
## Press Q to exit.FALSE
## Called from: doSetupTypeInference_processNF(setupSymTab, outputNames, instances, 
##   add = TRUE)
## Browse[1]> 
## debug: if (add) symTab$addSymbol(symbolRCobject)
## Browse[2]> Q
## Warning message:
## In makeTypeObject(name, instances, firstOnly) :
##   Problem, dimensions do no all match for neighborWeights
```

Other notes:

1. In the above example, if you comment *out* the line `for(i in 1:L) {   weights[i] <- 1   }`, and *uncomment* the line `##weights = rep(1,4),`, this will get through the compiler.
1. I suspect the issue is coming from.  Nested in here:
`Rmcmc$samplerFunctions[[1]]$componentSamplerFunctions[[1]]$dcar$neighborWeights`
`Rmcmc$samplerFunctions[[1]]$componentSamplerFunctions[[2]]$dcar$neighborWeights`
`Rmcmc$samplerFunctions[[1]]$componentSamplerFunctions[[3]]$dcar$neighborWeights`

are vectors of `neighborWeights`, and from the warning message, it seems the length-1 ones are being inferred as scalars, and length-2 being inferred as a vector, causing the problem.

**Comment by perrydv** [comment] 2017-06-14 00:01
I am unable to reproduce this error outside of the `car` context.  Here is the example I tried on branch `devel`:

```{r}
library(nimble)

m <- nimbleModel(
    nimbleCode({
        for(i in 1:L) x[i] <- 1
        a ~ dnorm(sum(x[1:L]), 1)
    }),
    constants = list(L = 3)
)

cm <- compileNimble(m, dirName = '.')
cm$x
```

When I install branch `car`, I can reproduce the example.  The warning message from `makeTypeObject` appears to be correctly informative.  If you run with `options(error = recover)` and when it stops look at ``lapply(instances, `[[`, 'neighborWeights')``, two are scalar and one is vector.  This is a known problem corner in `nimbleFunction`s: all instances must have the same type for the same variables.  Workaround is to ensure they are all vectors and adjust in run code as needed.

Next question is why do we get different behavior between the two ways of setting up `weights` in your reproducible example.  I got as far as seeing that `Rmodel$getParam('S[1:3]', 'weights')` returns a 1D array in one case and a vector in another case.  This touches issues we've run into before about trying to ensure that the active bindings for model variables return consistent types.  It looks like `sampler_CAR_normal` calls `weights <- Rmodel$getParam('S[1:3]', 'weights')` (where `target` is `S[1:3]`).  Does any subsequent processing with `weights` behave differently for 1D array vs vector?  Can you take it from here @danielturek ?

**Comment by danielturek** [comment] 2017-06-14 13:24
@perrydv, for now I made a workaround in the CAR code so this isn't an issue.  Will revisit the deeper issue later.

**Comment by perrydv** [comment] 2017-06-14 16:06
@danielturek Sounds good.  I am closing this issue now.  You can open a new issue with more refined topic if necessary.   As of now it is not clear if the current topic qualifies as a bug.

**Closed by perrydv** 2017-06-14 16:06 UTC
