### ISSUE TITLE
avoid need to lift boolean arithmetic expressions that are part of distribution parameter expressions

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#24] opened 2015-05-03 21:37 UTC
Currently if we have
mu.c ~ dconstraint(mu < 1)
 the user needs to manually lift mu<1:
ind <- mu<1
mu.c ~ dconstraint(ind)

I believe this arises more generally when using a boolean expression as a distribution argument/parameter.

**Comment by danielturek** [comment] 2015-05-04 16:29
For the record, I'm not entirely clear on what the problem is, or what the (more desirable) handling would be?  Can you please clarify, Chris?

**Comment by paciorek** [comment] 2015-05-04 16:32
I think it would be nice to allow:

mu.c ~ dconstraint(mu < 1)

or as a more important use case something like this, for splines, say

y[i] ~ dnorm(b0 + b1 * x[i] + b2* (x[i] - knot) * (x[i] > knot), 1)

**Comment by perrydv** [comment] 2015-05-14 20:36
This was redundant with issue 59 and is now fixed.

**Closed by perrydv** 2015-05-14 20:36 UTC
Labels: enhancement
