### ISSUE TITLE
Correct functioning of `split = TRUE` in `buildLaplace` and `buildAGHQuad` ?

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#1315] opened 2023-05-12 19:35 UTC
@weizhangstats @perrydv @paul-vdb 

Recognizing upfront I might be wrong about this, and the functionality I'm seeing is intentional and correct.

However, I'm not fully understanding how the `split = TRUE` control argument is functioning for `buildLaplace` / `buildAGHQuad`.

By my understanding, this argument (when `split = TRUE`) is used to split the RE nodes into conditionally independent groups, thereby allowing the approximation to operate separately over smaller (conditionally independent) groups, to generate the desired likelihood approximation.

That's not exactly what I see happening.  As a result of `setupMargNodes` using `model$getConditionallyIndependentSets` to generate conditionally independent sets of model nodes, and the result of this (`MargNodes$randomEffectsSets`) later being used to "divide the random effects into conditionally independent sets", it seems that `split = TRUE` is oftentimes introducing (potentially huge numbers of) new "random effects" nodes into the nested `buildOneAGHQuad` or `buildOneAGHQuad1D` functions.

A short example of this, although it can easily be many, many more nodes being introduced as "random effects":
```
library(nimble)

code <- nimbleCode({
    ## parameters:
    p1 ~ dnorm(0, 1)
    p2 ~ dnorm(0, 1)
    ## random effect:
    re1 ~ dnorm(p1, 1)
    ## data:
    y ~ dnorm(re1 + p2, 1)
})

Rmodel <- nimbleModel(code, data = list(y=0))

## When split = FALSE, this looks correct.
## The RE nodes are "re1":
Rlaplace <- buildLaplace(Rmodel, 'p1', 're1', control = list(split = FALSE))
Rlaplace$AGHQuad_nfl[[1]]$randomEffectsNodes
## "re1"

## When split = TRUE (the default),
## one additional "random effect" node is introduced ("p2"):
Rlaplace <- buildLaplace(Rmodel, 'p1', 're1')   ## uses default split = TRUE
Rlaplace$AGHQuad_nfl[[1]]$randomEffectsNodes
## "p2"  "re1"
```

Maybe this is correct-by-design, and I need to think more carefully about why.  But this seems suspicious to me.

It makes me wonder, for example, if line 1436 of `Laplace.R` should instead be more like:
```
reSets <- MargNodes$randomEffectsSets
## remove any nodes within reSets which are not among scalarRENodes:
reSets <- lapply(reSets, function(set) intersect(set, scalarRENodes))
## remove any elements of reSets which are zero-length:
reSets <- reSets[sapply(reSets,length) > 0]
```

**Comment by weizhangstats** [comment] 2023-05-13 13:40
Thanks @danielturek. The point here is that only `p1` is specified as a parameter while `p2` should be as well. Then from the output everything seems correct except for the additional `p2` as a random effect incorrectly. I think this comes from the call of `getConditionallyIndependentSets` on line1307-1309 of `Laplace.R`:
```
reSets <- Rmodel$getConditionallyIndependentSets(nodes = "re1", givenNodes = c("y", "p1"), 
unknownAsGiven = allowNonPriors) ## allowNonPriors = FALSE now
```
Given `unknownAsGiven` is FALSE, `getConditionallyIndependentSets` will automatically add stochastic nodes (i.e. `p2` here) that are not included in either `nodes` or `givenNodes` into `nodes` and then group them. Then the result is reasonable. Setting `unknownAsGiven = TRUE` will give only `re1` as expected. @perrydv, is there any reason why we need to set `unknownAsGiven = FALSE` here? To me it seems more reasonable to set it to be `TRUE` because we do not want to unexpectedly treat some nodes as random effects? I think you explained it somewhere before, but I cannot remember.

**Comment by perrydv** [comment] 2023-05-13 15:48
Hi @weizhangstats @danielturek , you've put your finger on it. As originally designed, `getConditionallyIndependentSets` was intended to use the RE nodes as starting points to explore all sets including nodes that are not "given". However you've both found cases where that gives results you did not expect. You are expecting that only those nodes provided as RE nodes will be included in the returned sets. Can we try changing to `unknownAsGiven=TRUE` and check on our tests and see if there are new kinds of non-intuitive cases with that setting or if it seems to make more intuitive sense?  What that does is treat a node like `p2`, which is of unknown status because it is neither given nor RE (when calling `getConditionallyIndependentSets`) as given, rather than as RE.

**Comment by paciorek** [comment] 2023-12-08 20:37
@perrydv @weizhangstats @danielturek can we close this issue? Or resolve it if it is not resolved?

**Comment by perrydv** [comment] 2023-12-15 20:25
We reworked `getConditionallyIndependentSets` a fair bit at the time of this Issue. Closing this.

**Closed by perrydv** 2023-12-15 20:25 UTC
