### ISSUE TITLE
silent errors in test-math and issues with XFAIL reporting in various tests

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#501] opened 2017-07-20 15:47 UTC
We still need some cleanup in test-math. There are errors that do not show an error message (e.g., "step of vector") and there are errors that go into a browser. We probably want to alter the code base so we don't invoke a browser in that setting as it's not clear to me whether that mucks up the behavior of the testing at all.

I won't set a milestone of 0.6-6 for this as I don't want to spend more time now monkeying with this, but @fritzo  or I should clean this up at some point.

**Comment by paciorek** [comment] 2017-07-20 15:50
similarly, test-size shows a number of:
```
BEGIN XFAIL
.END XFAIL
```
with no error msg displayed. We should discuss if this is the behavior we want.

**Comment by paciorek** [comment] 2017-07-20 15:54
And in test-returnErrorTypeTrapping, the first two tests (and likely more) are cases where Nimble correctly doesn't compile. I don't think these are "expected failures". An expected failure is where something doesn't work and we'd like to to work in Nimble but we haven't enabled the functionality. Here these are cases where we expect an error and we get one. So our wrapping of expect_error() here seems faulty to me.

**Comment by fritzo** [comment] 2017-07-20 16:40
@paciorek note the difference between `expect_error()` and `expect_failure()`. In `test-returnErrorTypeTrapping.R` we are correctly using `expect_error()` to assert that Nimble complains about compiling invalid programs. In other tests, e.g. in some `test-math.R` tests, we `expect_failure()` when Nimble incorrectly crashes during compilation.

**Comment by fritzo** [comment] 2017-07-20 16:43
Re: `browser()` I recommend expunging all use of `browser()` from released code.

**Comment by paciorek** [comment] 2017-07-20 16:44
@fritzo I'm not understanding. If Nimble fails to compile because of a user error in programming a nimbleFunction we expect an error as you say, but I don't think that is an "expected failure" that should produce an XFAIL in our test log for returnErrorTypeTrapping. Probably best discussed in person when I see you...

**Comment by fritzo** [comment] 2017-07-20 16:48
@paciorek Yes let's discuss in person. I'm interested in your process of manually inspecting logs; perhaps we can automate some of that.

**Comment by fritzo** [comment] 2017-07-20 17:36
@paciorek Ok I can reproduce a silent failure in `test-RefactorCompilationSteps.R`, the silencing should hopefully be fixed by #503, and I'm working on making the math error system more precise to fix the errors.

**Comment by fritzo** [comment] 2017-08-08 16:16
Closing, since this appears to have been fixed by #504.

**Closed by fritzo** 2017-08-08 16:16 UTC
Labels: cleanup
